#!/usr/bin/env bash
# Publishes each Linux bundle listed in linux/bundles.json as a release of this repository (#34).
# Generated by kyle-lt/OtelSiteExtension (build/install/public/); edits here are overwritten.
#
# The installers in this repository download the bundle from these releases, so GitHub's public
# per-asset download count counts installs. Nothing else is collected, by anyone.
#
# Each asset is the distribution's own release asset, byte for byte: it's downloaded from the
# source release and must match the pinned sha256 before it is uploaded. An asset that is already
# here is left alone if its digest matches, and is an error if it doesn't or if GitHub gives none.
# It is never replaced: replacing would reset its count, and a pinned version's bytes don't change.
#
#   GH_REPO=owner/repo GH_TOKEN=... release-bundles.sh linux/bundles.json
set -euo pipefail

manifest=${1:?usage: release-bundles.sh <bundles.json>}
: "${GH_REPO:?set GH_REPO to the repository to release in}"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

sha256() { if command -v sha256sum >/dev/null; then sha256sum "$1"; else shasum -a 256 "$1"; fi | cut -d' ' -f1; }
field() { jq -er --arg t "$1" --arg f "$2" '.[$t][$f]' "$manifest"; }

for tag in $(jq -r 'keys[]' "$manifest"); do
  asset=$(field "$tag" asset); source=$(field "$tag" source); want=$(field "$tag" sha256)

  # gh prints the 404 body to stdout, so the exit status and stderr decide, not the output. Only a
  # 404 means "not released yet"; any other failure (auth, network, rate limit) stops the run.
  if release=$(gh api "repos/$GH_REPO/releases/tags/$tag" 2>"$work/err"); then
    :
  elif grep -q "HTTP 404" "$work/err"; then
    release=""
  else
    echo "::error::$tag: couldn't read the release: $(cat "$work/err")"; exit 1
  fi
  if [ -n "$release" ]; then
    digest=$(jq -r --arg a "$asset" '.assets[] | select(.name == $a) | .digest // "none"' <<<"$release")
    case $digest in
      "sha256:$want") echo "$tag: $asset already published, digest matches"; continue ;;
      none) echo "::error::$tag: GitHub gives no digest for the published $asset, so it can't be checked against the pin."; exit 1 ;;
      "") ;;  # the release exists without the asset: an earlier run stopped half-way
      *) echo "::error::$tag: the published $asset has digest $digest, pinned sha256:$want. Not replacing it."; exit 1 ;;
    esac
  fi

  echo "$tag: downloading $source"
  curl -fsSL --retry 5 --retry-all-errors -o "$work/$asset" "$source"
  got=$(sha256 "$work/$asset")
  if [ "$got" != "$want" ]; then
    echo "::error::$tag: $source has sha256 $got, pinned $want. Not publishing it."; exit 1
  fi

  if [ -n "$release" ]; then
    gh release upload "$tag" "$work/$asset"
  else
    gh release create "$tag" "$work/$asset" --title "$(field "$tag" title)" --notes "$(field "$tag" notes)" \
      --target "${GITHUB_SHA:-main}" --latest=false
  fi
  echo "$tag: published $asset (sha256 $want)"
done
