// Install OpenTelemetry .NET automatic instrumentation on an existing Linux App Service app (#28).
// Deploy into the app's resource group:
//   az deployment group create -g <resource-group> -f otel-dotnet-linux.bicep -p appName=<app> distro=upstream
//
// In order, with no race: the distro's own release zip is unzipped onto the app's /home
// (`onedeploy`, no restart), and only then are the activation App Settings merged into the app's
// own, which restarts it with the files already there.
//
// Generated by build/installer.py from distros.json and the bundles' own instrument.sh. Edit
// build/install/otel-dotnet-linux.bicep.tmpl, not this file.

@description('Name of an existing Linux web app (built-in .NET image) in this resource group.')
param appName string

@description('Which distribution to install.')
@allowed(['upstream', 'splunk'])
param distro string = 'upstream'

var distros = {
  upstream: {
    packageUri: 'https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/download/v1.17.0/opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip'
    target: '/home/otel/upstream/1.17.0'
    settings: {
      CORECLR_ENABLE_PROFILING: '1'
      CORECLR_PROFILER: '{918728DD-259F-4A6A-AC2B-B85E1B658318}'
      CORECLR_PROFILER_PATH: '/home/otel/upstream/1.17.0/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so'
      OTEL_DOTNET_AUTO_HOME: '/home/otel/upstream/1.17.0'
      OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES: 'DiagServer'
    }
  }
  splunk: {
    packageUri: 'https://github.com/signalfx/splunk-otel-dotnet/releases/download/v1.16.0/splunk-opentelemetry-dotnet-linux-glibc-x64.zip'
    target: '/home/otel/splunk/1.16.0'
    settings: {
      CORECLR_ENABLE_PROFILING: '1'
      CORECLR_PROFILER: '{918728DD-259F-4A6A-AC2B-B85E1B658318}'
      CORECLR_PROFILER_PATH: '/home/otel/splunk/1.16.0/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so'
      OTEL_DOTNET_AUTO_HOME: '/home/otel/splunk/1.16.0'
      OTEL_DOTNET_AUTO_PLUGINS: 'Splunk.OpenTelemetry.AutoInstrumentation.Plugin, Splunk.OpenTelemetry.AutoInstrumentation'
      OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES: 'DiagServer'
    }
  }
}
var d = distros[distro]

resource site 'Microsoft.Web/sites@2024-04-01' existing = {
  name: appName
}

// Kudu fetches the zip from the distro's GitHub release. Unlike install.sh, this path can't check
// the sha256 pin itself: it trusts the tag-pinned release asset at deploy time.
#disable-next-line BCP187
resource bundle 'Microsoft.Web/sites/extensions@2024-04-01' = {
  parent: site
  name: 'onedeploy'
  properties: {
    packageUri: d.packageUri
    type: 'zip'
    path: d.target
    restart: false
    clean: false
  }
}

// A module, so the app's current settings are read here and merged there (a direct PUT of
// appsettings replaces every setting the app has).
module settings 'otel-appsettings.bicep' = {
  name: 'otel-appsettings-${uniqueString(appName)}'
  dependsOn: [ bundle ]
  params: {
    appName: appName
    currentAppSettings: list(resourceId('Microsoft.Web/sites/config', appName, 'appsettings'), '2024-04-01').properties
    otelSettings: d.settings
  }
}
