#!/usr/bin/env bash
# Install OpenTelemetry .NET automatic instrumentation on a Linux Azure App Service app (#28).
#
#   bash install.sh -g <resource-group> -n <app> [--distro upstream|splunk] [--slot <slot>] [--dry-run]
#   bash install.sh -g <resource-group> -n <app> --uninstall
#
# Runs in Azure Cloud Shell (it needs az, curl and python3, signed in). In order, with no race:
#   1. checks the app is a Linux app on the built-in .NET image, with no other .NET profiler;
#   2. downloads the pinned bundle, checks its sha256, and pushes it onto the app's /home through
#      Kudu (skipped when that version is already there);
#   3. merges the activation App Settings into the app's own (never replaces them). That restarts
#      the app, and this start finds the files already there.
#
# Generated by build/installer.py from distros.json and the bundles' own instrument.sh. Don't edit
# the generated file: edit build/install/install.sh.tmpl.
set -euo pipefail

DISTROS_JSON=$(cat <<'JSON'
{
  "upstream": {
    "name": "OpenTelemetry .NET automatic instrumentation",
    "version": "1.17.0",
    "package_uri": "https://github.com/kyle-lt/kjt-dotnet-azureappservices/releases/download/upstream-1.17.0/opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip",
    "source_uri": "https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/download/v1.17.0/opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip",
    "sha256": "cc56878f0155e28b6554924fbd420fcb8bec7108cd9d41836dc530764ac923f8",
    "target": "/home/otel/upstream/1.17.0",
    "settings": {
      "CORECLR_ENABLE_PROFILING": "1",
      "CORECLR_PROFILER": "{918728DD-259F-4A6A-AC2B-B85E1B658318}",
      "CORECLR_PROFILER_PATH": "/home/otel/upstream/1.17.0/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so",
      "OTEL_DOTNET_AUTO_HOME": "/home/otel/upstream/1.17.0",
      "OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES": "DiagServer"
    },
    "next_step": "Set your OTLP endpoint (and headers, if your backend needs auth), for example:\n  az webapp config appsettings set -g {rg} -n {app} --settings OTEL_SERVICE_NAME=<name> OTEL_EXPORTER_OTLP_ENDPOINT=<https://your-endpoint> \"OTEL_EXPORTER_OTLP_HEADERS=<header>=<secret>\""
  },
  "splunk": {
    "name": "Splunk Distribution of OpenTelemetry .NET",
    "version": "1.16.0",
    "package_uri": "https://github.com/kyle-lt/kjt-dotnet-azureappservices/releases/download/splunk-1.16.0/splunk-opentelemetry-dotnet-linux-glibc-x64.zip",
    "source_uri": "https://github.com/signalfx/splunk-otel-dotnet/releases/download/v1.16.0/splunk-opentelemetry-dotnet-linux-glibc-x64.zip",
    "sha256": "3801716bbf0094c423c5c6b586e38b52f383aa1bc9c6bd4177bf4f3f6e32c384",
    "target": "/home/otel/splunk/1.16.0",
    "settings": {
      "CORECLR_ENABLE_PROFILING": "1",
      "CORECLR_PROFILER": "{918728DD-259F-4A6A-AC2B-B85E1B658318}",
      "CORECLR_PROFILER_PATH": "/home/otel/splunk/1.16.0/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so",
      "OTEL_DOTNET_AUTO_HOME": "/home/otel/splunk/1.16.0",
      "OTEL_DOTNET_AUTO_PLUGINS": "Splunk.OpenTelemetry.AutoInstrumentation.Plugin, Splunk.OpenTelemetry.AutoInstrumentation",
      "OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES": "DiagServer"
    },
    "next_step": "For Splunk Observability Cloud, for example:\n  az webapp config appsettings set -g {rg} -n {app} --settings OTEL_SERVICE_NAME=<name> SPLUNK_REALM=<realm> SPLUNK_ACCESS_TOKEN=<token>\nOr any OTLP endpoint, with OTEL_EXPORTER_OTLP_ENDPOINT."
  }
}
JSON
)
MARKER=.otel-installed

usage() {
  cat <<'USAGE'
bash install.sh -g <resource-group> -n <app> [--distro upstream|splunk] [--slot <slot>] [--dry-run]
bash install.sh -g <resource-group> -n <app> --uninstall
USAGE
  exit "${1:-0}"
}
say() { echo "$*"; }
die() { echo "error: $*" >&2; exit 1; }

RG= APP= SLOT= DISTRO=upstream DRY=0 UNINSTALL=0
while [ $# -gt 0 ]; do
  case "$1" in
    -g|--resource-group) RG=${2:?}; shift 2 ;;
    -n|--name) APP=${2:?}; shift 2 ;;
    --slot) SLOT=${2:?}; shift 2 ;;
    --distro) DISTRO=${2:?}; shift 2 ;;
    --dry-run) DRY=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    -h|--help) usage 0 ;;
    *) echo "unknown argument: $1" >&2; usage 2 ;;
  esac
done
[ -n "$RG" ] && [ -n "$APP" ] || usage 2
for c in az curl python3; do command -v "$c" >/dev/null || die "$c is needed (Azure Cloud Shell has it)"; done

field() { python3 -c 'import json,sys; d=json.loads(sys.argv[1]); print(d[sys.argv[2]][sys.argv[3]] if sys.argv[2] in d else "")' "$DISTROS_JSON" "$DISTRO" "$1"; }
[ -n "$(field version)" ] || die "unknown distro '$DISTRO' (choose: $(python3 -c 'import json,sys; print(", ".join(json.loads(sys.argv[1])))' "$DISTROS_JSON"))"
NAME=$(field name); VERSION=$(field version); URL=$(field package_uri); SHA=$(field sha256); TARGET=$(field target)
VFS_DIR=${TARGET#/home/}
SLOT_ARGS=(); [ -n "$SLOT" ] && SLOT_ARGS=(--slot "$SLOT")

# --- 1. The app ---------------------------------------------------------------------------------
say "Checking $APP${SLOT:+ (slot $SLOT)} ..."
info=$(az webapp show -g "$RG" -n "$APP" ${SLOT_ARGS[@]+"${SLOT_ARGS[@]}"} -o json) || die "can't read the app (signed in to the right subscription? az account show)"
current=$(az webapp config appsettings list -g "$RG" -n "$APP" ${SLOT_ARGS[@]+"${SLOT_ARGS[@]}"} -o json)
read -r KIND FX SCM < <(python3 -c '
import json,sys
a=json.loads(sys.argv[1])
scm=next((h for h in a.get("enabledHostNames",[]) if ".scm." in h), "")
print(a.get("kind",""), (a.get("siteConfig") or {}).get("linuxFxVersion") or "-", scm or "-")' "$info")
case "$KIND" in *linux*) ;; *) die "$APP is not a Linux app. On Windows, use the site extension (Extensions -> Add) instead." ;; esac
case "$FX" in DOTNETCORE\|*) ;; *) die "$APP runs '$FX'. This installs into apps on the built-in .NET image (DOTNETCORE|...), not custom containers." ;; esac
[ "$SCM" != "-" ] || die "can't find $APP's Kudu (SCM) host name"

setting() { python3 -c 'import json,sys; print(next((s["value"] or "" for s in json.loads(sys.argv[1]) if s["name"]==sys.argv[2]), ""))' "$current" "$1"; }
ours() { python3 -c 'import json,sys; print(json.loads(sys.argv[1])[sys.argv[2]]["settings"].get(sys.argv[3],""))' "$DISTROS_JSON" "$DISTRO" "$1"; }

# --- Uninstall ----------------------------------------------------------------------------------
if [ "$UNINSTALL" = 1 ]; then
  # Only settings that still hold this distro's value, so nothing the operator changed is removed.
  names=$(python3 -c '
import json,sys
cur={s["name"]:s["value"] for s in json.loads(sys.argv[1])}
want=json.loads(sys.argv[2])[sys.argv[3]]["settings"]
print(" ".join(n for n,v in want.items() if n!="OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES" and cur.get(n)==v))' "$current" "$DISTROS_JSON" "$DISTRO")
  [ -n "$names" ] || die "none of $NAME $VERSION's settings are on $APP"
  say "Removing App Settings: $names"
  [ "$DRY" = 1 ] && { say "(dry run: nothing changed)"; exit 0; }
  # shellcheck disable=SC2086
  az webapp config appsettings delete -g "$RG" -n "$APP" ${SLOT_ARGS[@]+"${SLOT_ARGS[@]}"} --setting-names $names -o none
  say "Done. $APP restarts without instrumentation. OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES and your OTEL_* settings were left alone."
  say "The files stay in $TARGET; delete that directory from Kudu once nothing points at it."
  exit 0
fi

profiler=$(setting CORECLR_PROFILER)
if [ -n "$profiler" ] && [ "$profiler" != "$(ours CORECLR_PROFILER)" ]; then
  die "$APP already has a .NET profiler configured (CORECLR_PROFILER=$profiler). The runtime loads one; remove the other first."
fi
[ -z "$(setting DOTNET_STARTUP_HOOKS)" ] || say "note: $APP sets DOTNET_STARTUP_HOOKS itself; that combination isn't tested."
exclude=$(python3 -c '
import sys
cur=[p.strip() for p in sys.argv[1].split(",") if p.strip()]
add=sys.argv[2]
print(",".join(cur + ([add] if add not in cur else [])))' "$(setting OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES)" "$(ours OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES)")

say "Installing $NAME $VERSION into $TARGET"
if [ "$DRY" = 1 ]; then
  say "(dry run) would push $URL (sha256 $SHA) to https://$SCM/api/zip/$VFS_DIR/ unless already there"
  say "(dry run) would merge these App Settings:"
  python3 -c 'import json,sys; s=json.loads(sys.argv[1])[sys.argv[2]]["settings"]; s["OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES"]=sys.argv[3]; [print(f"  {k}={v}") for k,v in s.items()]' "$DISTROS_JSON" "$DISTRO" "$exclude"
  exit 0
fi

# --- 2. The files -------------------------------------------------------------------------------
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
TOKEN=$(az account get-access-token --query accessToken -o tsv)
kudu() { curl -sS -H "Authorization: Bearer $TOKEN" "$@"; }
if [ "$(kudu -o /dev/null -w '%{http_code}' "https://$SCM/api/vfs/$VFS_DIR/$MARKER")" = 200 ]; then
  say "Already on /home: $TARGET"
else
  say "Downloading $URL ..."
  curl -fsSL --retry 3 -o "$tmp/bundle.zip" "$URL"
  got=$(python3 -c 'import hashlib,sys; print(hashlib.sha256(open(sys.argv[1],"rb").read()).hexdigest())' "$tmp/bundle.zip")
  [ "$got" = "$SHA" ] || die "sha256 mismatch: got $got, pinned $SHA. Not installing."
  say "sha256 ok. Pushing it onto /home through Kudu ..."
  code=$(kudu -X PUT --data-binary @"$tmp/bundle.zip" -o "$tmp/out" -w '%{http_code}' "https://$SCM/api/zip/$VFS_DIR/")
  [ "$code" = 200 ] || die "Kudu returned HTTP $code: $(head -c 300 "$tmp/out")"
  echo "$NAME $VERSION, sha256 $SHA, installed $(date -u +%FT%TZ) by install.sh" > "$tmp/marker"
  code=$(kudu -X PUT -H 'If-Match: *' --data-binary @"$tmp/marker" -o /dev/null -w '%{http_code}' "https://$SCM/api/vfs/$VFS_DIR/$MARKER")
  case "$code" in 200|201|204) ;; *) die "couldn't write $TARGET/$MARKER (HTTP $code)";; esac
  say "Installed in $TARGET"
fi

# --- 3. The settings ----------------------------------------------------------------------------
python3 -c '
import json,sys
s=json.loads(sys.argv[1])[sys.argv[2]]["settings"]; s["OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES"]=sys.argv[3]
json.dump([{"name":k,"value":v,"slotSetting":False} for k,v in s.items()], open(sys.argv[4],"w"))' "$DISTROS_JSON" "$DISTRO" "$exclude" "$tmp/settings.json"
say "Setting the App Settings (merged with yours; this restarts the app) ..."
az webapp config appsettings set -g "$RG" -n "$APP" ${SLOT_ARGS[@]+"${SLOT_ARGS[@]}"} --settings @"$tmp/settings.json" -o none

cat <<EOF

Done. $APP is restarting with $NAME $VERSION switched on.

Still needed: where to send the data.
$(field next_step | sed -e "s|{rg}|$RG|g" -e "s|{app}|$APP|g")
EOF
