# Install OpenTelemetry .NET automatic instrumentation on a Linux App Service app (#28).
#
#   module "otel" {
#     source = "<path or URL to this module>"
#     app_id = azurerm_linux_web_app.app.id
#     distro = "upstream"
#   }
#
#   resource "azurerm_linux_web_app" "app" {
#     ...
#     app_settings = merge(local.my_settings, module.otel.app_settings)
#   }
#
# The settings are constants, so your web app keeps owning them. This module unzips the distro's
# release onto the app's /home (`onedeploy`, no restart) and then restarts the app once, so it
# starts with the files there whichever order Terraform applied things in.
#
# Generated by build/installer.py. Edit build/install/terraform/main.tf.tmpl, not this file.

terraform {
  required_providers {
    azapi = {
      source  = "Azure/azapi"
      version = ">= 2.0"
    }
  }
}

variable "app_id" {
  description = "Resource ID of an existing Linux web app on the built-in .NET image."
  type        = string
}

variable "distro" {
  description = "Which distribution to install."
  type        = string
  default     = "upstream"
  validation {
    condition     = contains(["upstream", "splunk"], var.distro)
    error_message = "distro must be one of: upstream, splunk."
  }
}

locals {
  distros = {
    upstream = {
      package_uri = "https://github.com/kyle-lt/kjt-dotnet-azureappservices/releases/download/upstream-1.17.0/opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip"
      target      = "/home/otel/upstream/1.17.0"
      settings = {
        CORECLR_ENABLE_PROFILING           = "1"
        CORECLR_PROFILER                   = "{918728DD-259F-4A6A-AC2B-B85E1B658318}"
        CORECLR_PROFILER_PATH              = "/home/otel/upstream/1.17.0/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so"
        OTEL_DOTNET_AUTO_HOME              = "/home/otel/upstream/1.17.0"
        OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES = "DiagServer"
      }
    }
    splunk = {
      package_uri = "https://github.com/kyle-lt/kjt-dotnet-azureappservices/releases/download/splunk-1.16.0/splunk-opentelemetry-dotnet-linux-glibc-x64.zip"
      target      = "/home/otel/splunk/1.16.0"
      settings = {
        CORECLR_ENABLE_PROFILING           = "1"
        CORECLR_PROFILER                   = "{918728DD-259F-4A6A-AC2B-B85E1B658318}"
        CORECLR_PROFILER_PATH              = "/home/otel/splunk/1.16.0/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so"
        OTEL_DOTNET_AUTO_HOME              = "/home/otel/splunk/1.16.0"
        OTEL_DOTNET_AUTO_PLUGINS           = "Splunk.OpenTelemetry.AutoInstrumentation.Plugin, Splunk.OpenTelemetry.AutoInstrumentation"
        OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES = "DiagServer"
      }
    }
  }
  d = local.distros[var.distro]
}

# Kudu fetches the zip from the public repo's release of it, an unmodified copy of the distro's own
# release asset (#34; this path can't check the sha256 itself, install.sh does). A PUT action, not an azapi_resource: every app deployed with
# `az webapp deploy` already has a `onedeploy` resource, and claiming it would fail with "already
# exists" (measured).
resource "azapi_resource_action" "bundle" {
  type        = "Microsoft.Web/sites/extensions@2024-04-01"
  resource_id = "${var.app_id}/extensions/onedeploy"
  method      = "PUT"
  body = {
    properties = {
      packageUri = local.d.package_uri
      type       = "zip"
      path       = local.d.target
      restart    = false
      clean      = false
    }
  }
}

# One restart once the files are there.
resource "azapi_resource_action" "restart" {
  type        = "Microsoft.Web/sites@2024-04-01"
  resource_id = var.app_id
  action      = "restart"
  method      = "POST"
  depends_on  = [azapi_resource_action.bundle]
  lifecycle {
    replace_triggered_by = [azapi_resource_action.bundle]
  }
}

output "app_settings" {
  description = "Merge these into your web app's app_settings. If you set OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES yourself, keep DiagServer in it."
  value       = local.d.settings
}
